name: Docker Build and Publish and Deploy to DeployAja

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/gonjali/absensi-laravel
  GH_REGISTRY: ghcr.io
  IMAGE_NAME: absensi-laravel
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: DeployAja Plan
        uses: deployaja/deployaja-cli@v0.0.17
        with:
          command: plan
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          
      - name: DeployAja Deploy
        uses: deployaja/deployaja-cli@v0.0.17
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          additional-args: |
            --set container.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --set env[12].value=${{ vars.DB_HOST }} \
            --set env[13].value=${{ vars.DB_DATABASE }} \
            --set env[14].value=${{ secrets.DB_USERNAME }} \
            --set env[15].value=${{ secrets.DB_PASSWORD }} \
            --set env[16].value=${{ vars.DB_PORT }}
          
      - name: DeployAja Status
        uses: deployaja/deployaja-cli@v0.0.17
        with:
          command: status
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
